name: Build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check ref name
        run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.event.pull_request.head.ref }}"

      - name: Check out the repo
        if: github.triggering_actor != 'dependabot[bot]'
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: github.triggering_actor != 'dependabot[bot]'
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: github.triggering_actor != 'dependabot[bot]'
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: nojussta/restoresa-frontend
          tags: v1.${{ github.run_number}}

      - name: Build and push Docker image
        if: github.triggering_actor != 'dependabot[bot]'
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
